2017-04-12 13:37:56,639 - MainServerlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-12 13:38:07,701 - MainServerlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 51704) : connect successfully!
2017-04-12 13:38:52,523 - MainServerlog -log.py[line:26]-INFO -a connection lost
2017-04-12 14:17:38,303 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-12 14:17:44,661 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 52556) : connect successfully!
2017-04-12 14:17:55,296 - Mainserverlog -log.py[line:26]-INFO -a connection lost
2017-04-12 14:17:56,335 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 52562) : connect successfully!
2017-04-12 14:17:56,864 - Mainserverlog -log.py[line:26]-INFO -a connection lost
2017-04-13 18:08:15,968 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:08:44,774 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:08:47,008 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 60921) : connect successfully!
2017-04-13 18:09:56,991 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:10:00,134 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 60955) : connect successfully!
2017-04-13 18:10:04,677 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:10:04,725 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-04-13 18:20:41,340 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:20:42,357 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 61254) : connect successfully!
2017-04-13 18:20:46,118 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:20:46,119 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-04-13 18:21:18,513 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:21:20,418 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 61279) : connect successfully!
2017-04-13 18:21:23,844 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:21:23,845 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:26:22,697 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:26:25,215 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 61407) : connect successfully!
2017-04-13 18:26:27,292 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:26:27,293 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:28:28,694 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:28:30,899 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 61477) : connect successfully!
2017-04-13 18:28:33,387 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:28:33,389 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:29:10,102 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:29:11,990 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 61504) : connect successfully!
2017-04-13 18:29:14,153 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:29:14,277 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:30:14,606 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:30:17,264 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 61536) : connect successfully!
2017-04-13 18:30:19,223 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:30:19,312 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:31:18,217 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:31:20,230 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 61650) : connect successfully!
2017-04-13 18:31:22,018 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:31:22,117 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:38:24,496 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:38:25,759 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 51880) : connect successfully!
2017-04-13 18:38:29,362 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:38:29,452 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:38:56,370 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:38:58,377 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 51910) : connect successfully!
2017-04-13 18:39:00,026 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:39:00,082 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:39:51,271 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:39:53,619 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 51939) : connect successfully!
2017-04-13 18:39:55,291 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:40:47,831 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:40:50,652 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 51971) : connect successfully!
2017-04-13 18:40:54,296 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:41:08,163 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:41:09,983 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 51990) : connect successfully!
2017-04-13 18:41:11,916 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:41:12,007 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:41:59,141 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:42:01,086 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 52016) : connect successfully!
2017-04-13 18:42:02,783 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:42:02,840 - Mainserverlog -log.py[line:26]-INFO -data insert wrong!
2017-04-13 18:45:56,964 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-13 18:46:00,361 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 52202) : connect successfully!
2017-04-13 18:46:02,132 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-13 18:46:02,219 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-04-14 10:26:04,055 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-14 10:26:05,474 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 58643) : connect successfully!
2017-04-14 10:26:07,829 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-14 10:26:07,955 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-04-14 10:57:34,473 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-14 10:57:36,217 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 62971) : connect successfully!
2017-04-14 10:57:39,093 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-14 10:57:39,177 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-04-14 10:57:57,191 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-14 10:57:58,444 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 62995) : connect successfully!
2017-04-14 10:58:00,606 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-14 10:58:00,656 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-04-14 10:58:03,567 - Mainserverlog -log.py[line:26]-INFO -IPv4Address(TCP, '127.0.0.1', 62995)
2017-04-14 10:58:55,399 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-14 10:58:56,398 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 63042) : connect successfully!
2017-04-14 10:58:59,720 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-14 10:58:59,818 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-04-14 10:59:02,351 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 63042) : lost connect
2017-04-16 10:48:07,302 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-16 10:49:42,629 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 58244) : connect successfully!
2017-04-16 10:49:51,574 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 58244) : lost connect
2017-04-16 10:50:41,258 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 58309) : connect successfully!
2017-04-16 10:50:43,894 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-16 10:50:43,964 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-04-16 10:50:54,287 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 58309) : lost connect
2017-04-16 11:06:37,253 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-16 11:06:46,918 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-16 11:09:17,248 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-16 11:09:22,383 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 65329) : connect successfully!
2017-04-16 11:09:22,434 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 65329) : lost connect
2017-04-16 11:10:22,489 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 65358) : connect successfully!
2017-04-16 11:10:22,491 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 65358) : lost connect
2017-04-16 11:13:42,518 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 65445) : connect successfully!
2017-04-17 21:28:14,277 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-17 21:57:30,304 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 21783) : connect successfully!
2017-04-17 21:57:34,594 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-17 21:57:34,595 - Mainserverlog -log.py[line:35]-ERROR -insert wrong!
2017-04-17 21:57:52,614 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-17 21:57:52,615 - Mainserverlog -log.py[line:35]-ERROR -insert wrong!
2017-04-17 22:03:58,628 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-17 22:03:58,696 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-04-17 22:51:09,825 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-17 22:51:12,705 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 22144) : connect successfully!
2017-04-17 22:52:38,246 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-17 22:52:40,084 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 22173) : connect successfully!
2017-04-23 20:25:25,793 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-23 20:25:48,706 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-23 20:26:40,496 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-23 20:26:43,460 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 55391) : connect successfully!
2017-04-23 20:26:48,311 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-23 20:26:48,311 - Mainserverlog -log.py[line:35]-ERROR -insert wrong!
2017-04-23 20:29:16,262 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-23 20:29:16,262 - Mainserverlog -log.py[line:35]-ERROR -insert wrong!
2017-04-23 20:30:21,144 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-04-23 20:30:44,395 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 55411) : connect successfully!
2017-04-23 20:30:47,203 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-04-23 20:30:47,390 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-03 12:10:33,965 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-03 12:12:10,230 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 38621) : connect successfully!
2017-05-03 12:12:22,906 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 38621) : lost connect
2017-05-03 16:17:41,292 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-03 16:19:59,564 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 52829) : connect successfully!
2017-05-03 16:20:53,198 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 52829) : lost connect
2017-05-06 11:32:03,227 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-06 11:32:10,053 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 3340) : connect successfully!
2017-05-06 11:32:15,912 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-06 11:32:15,978 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-06 11:32:37,546 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 3340) : lost connect
2017-05-06 11:32:39,493 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 3343) : connect successfully!
2017-05-06 11:32:41,798 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-06 11:32:41,861 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-06 13:13:33,529 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-06 13:14:32,673 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45742) : connect successfully!
2017-05-06 13:14:46,624 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45742) : lost connect
2017-05-06 13:16:02,199 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45743) : connect successfully!
2017-05-06 13:16:04,165 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45743) : lost connect
2017-05-06 13:19:08,631 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45744) : connect successfully!
2017-05-06 13:19:17,358 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45744) : lost connect
2017-05-06 13:20:55,381 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45745) : connect successfully!
2017-05-06 13:21:01,989 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45745) : lost connect
2017-05-06 13:29:36,058 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-06 13:29:42,179 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45746) : connect successfully!
2017-05-06 13:29:46,616 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 45746) : lost connect
2017-05-07 13:21:15,884 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-07 13:21:25,024 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.2', 42691) : connect successfully!
2017-05-07 13:21:27,458 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.2', 42691) : lost connect
2017-05-08 22:07:06,559 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-08 22:07:24,389 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.2', 60156) : connect successfully!
2017-05-08 22:07:28,980 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-08 22:07:29,035 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-08 22:07:35,376 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-08 22:07:35,436 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-08 22:07:50,976 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.2', 60156) : lost connect
2017-05-13 22:03:55,220 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-13 22:04:38,745 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54266) : connect successfully!
2017-05-13 22:04:39,241 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:39,342 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:39,523 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:39,541 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:39,829 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:39,852 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:40,033 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:40,074 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:40,234 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:40,252 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:40,435 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:40,462 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:40,635 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:40,661 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:40,837 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:40,861 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:41,038 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:41,061 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:41,238 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:41,261 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:41,440 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:41,461 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:41,641 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:41,671 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:41,842 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:41,860 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:42,043 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:42,060 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:42,244 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:42,271 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:42,445 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:42,471 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:42,647 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:42,670 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:42,849 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:42,870 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:43,048 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:43,069 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:43,250 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:43,270 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:43,456 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:43,480 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:43,652 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:43,669 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:43,855 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:43,879 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:44,054 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:44,079 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:44,255 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:44,278 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:44,456 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:44,479 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:44,656 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:44,678 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:44,858 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:44,878 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:45,059 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:45,089 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:45,260 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:45,277 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:45,461 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:45,477 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:45,662 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:45,688 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:45,863 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:45,954 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:46,094 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:46,132 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:46,293 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:46,320 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:46,495 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:46,542 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:46,700 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:46,719 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:46,897 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:46,919 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:47,097 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:47,141 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:47,299 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:47,319 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:47,499 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:47,518 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:47,701 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:47,718 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:47,902 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:47,929 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:48,103 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:48,128 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:48,304 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:48,339 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:48,508 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:48,539 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:48,713 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:48,739 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:48,909 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:48,927 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:49,108 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:49,127 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:49,311 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:49,327 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:49,510 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:49,526 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:49,712 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:49,737 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:49,913 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:49,948 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:50,113 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:50,136 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:50,315 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:50,336 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:50,515 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:50,536 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:50,716 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:50,736 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:50,918 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:50,936 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:51,119 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:51,135 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:51,320 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:51,346 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:51,521 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:51,546 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:51,722 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:51,745 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:51,923 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:51,945 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:52,124 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:52,144 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:52,326 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:52,345 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:52,527 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:52,544 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:52,727 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:52,755 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:52,929 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:52,955 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:53,129 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:53,154 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:53,330 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:53,354 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:53,533 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:53,554 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:53,732 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:53,753 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:53,934 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:53,975 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:54,135 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:54,152 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:54,336 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:54,353 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:54,538 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:54,563 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:54,738 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:54,763 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:54,939 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:54,962 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:55,140 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:55,162 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:55,341 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:55,373 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:55,542 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:55,573 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:55,743 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:55,761 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:55,945 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:55,962 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:56,145 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:56,172 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:56,346 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:56,372 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:56,547 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:56,582 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:56,748 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:56,781 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:56,951 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:56,971 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:57,153 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:57,181 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:57,351 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:57,370 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:57,552 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:57,569 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:57,753 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:57,769 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:57,955 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:57,980 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:58,172 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:58,202 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:58,367 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:58,390 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:58,568 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:58,590 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:58,769 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:58,790 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:58,970 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:58,990 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:59,171 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:59,188 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:59,373 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:59,400 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:59,573 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:59,600 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:59,774 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:59,800 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:04:59,975 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:04:59,999 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:00,176 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:00,199 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:00,378 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:00,399 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:00,583 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:00,609 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:00,779 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:00,820 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:00,981 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:00,998 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:01,182 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:01,209 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:01,383 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:01,420 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:01,584 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:01,608 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:01,785 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:01,807 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:01,986 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:02,007 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:02,187 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:05:02,219 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:05:02,390 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54266) : lost connect
2017-05-13 22:09:42,810 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54267) : connect successfully!
2017-05-13 22:09:42,973 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54267) : lost connect
2017-05-13 22:10:11,443 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54268) : connect successfully!
2017-05-13 22:10:11,583 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:11,621 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:11,810 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:11,832 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:12,014 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:12,032 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:12,214 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:12,243 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:12,415 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:12,442 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:12,616 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:12,642 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:12,817 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:12,841 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:13,019 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:13,064 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:13,219 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:13,240 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:13,420 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:13,462 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:13,623 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:13,651 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:13,823 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:13,840 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:14,026 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:14,050 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:14,224 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:14,250 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:14,426 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:14,461 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:14,627 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:14,650 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:14,827 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:14,848 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:15,029 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:15,049 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:15,230 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:15,249 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:15,431 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:15,448 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:15,638 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:15,671 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:15,835 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:15,870 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:16,034 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:16,059 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:16,236 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:16,259 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:16,436 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:16,458 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:16,642 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:16,658 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:16,838 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:16,858 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:17,040 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:17,069 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:17,240 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:17,257 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:17,441 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:17,468 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:17,643 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:17,668 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:17,844 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:17,867 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:18,045 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:18,067 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:18,245 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:18,267 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:18,447 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:18,478 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:18,648 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:18,665 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:18,850 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:18,876 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:19,050 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:19,076 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:19,251 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:19,276 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:19,452 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:19,476 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:19,653 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:19,675 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:19,858 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:19,897 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:20,055 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:20,075 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:20,257 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:20,275 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:20,459 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:20,486 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:20,658 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:20,685 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:20,860 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:20,909 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:21,060 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:21,130 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:21,270 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:21,296 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:21,470 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:21,495 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:21,672 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:21,694 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:21,872 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:21,894 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:22,073 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:22,094 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:22,275 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:22,305 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:22,475 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:22,515 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:22,676 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:22,693 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:22,878 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:22,893 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:23,078 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:23,103 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:23,279 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:23,303 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:23,481 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:23,515 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:23,681 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:23,703 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:23,882 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:23,902 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:24,084 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:24,103 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:24,285 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:24,302 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:24,486 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:24,501 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:24,687 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:24,713 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:24,888 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:24,912 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:25,107 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:25,134 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:25,290 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:25,311 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:25,491 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:25,511 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:25,692 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:25,711 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:25,895 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:25,911 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:26,094 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:26,121 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:26,296 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:26,321 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:26,496 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:26,520 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:26,698 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:26,721 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:26,898 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:26,954 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:27,134 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:27,186 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:27,327 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:27,353 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:27,527 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:27,553 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:27,730 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:27,752 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:27,928 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:27,963 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:28,129 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:28,162 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:28,330 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:28,351 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:28,532 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:28,551 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:28,733 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:28,751 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:28,933 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:28,949 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:29,134 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:29,150 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:29,336 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:29,545 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:29,683 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:10:29,727 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:10:29,885 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54268) : lost connect
2017-05-13 22:11:44,296 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54269) : connect successfully!
2017-05-13 22:11:46,244 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:11:46,321 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:11:48,338 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:11:48,395 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:11:50,349 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:11:50,458 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:11:52,406 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:11:52,478 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:11:54,426 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:11:54,530 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:11:56,479 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:11:56,594 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:11:58,541 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:11:58,635 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:00,584 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:12:00,687 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:02,641 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:12:02,740 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:04,691 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:12:04,726 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:06,700 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:12:06,767 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:08,716 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:12:08,842 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:10,790 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:12:11,138 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:13,088 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:12:13,124 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:15,099 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:12:15,131 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:17,112 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:12:17,140 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:12:19,167 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54269) : lost connect
2017-05-13 22:14:26,243 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-13 22:41:17,577 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-13 22:42:43,623 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54280) : connect successfully!
2017-05-13 22:42:45,580 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:42:45,641 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:42:47,590 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:42:47,648 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:42:49,600 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:42:49,657 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:42:51,610 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:42:51,664 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:42:53,621 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:42:53,662 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:42:55,632 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:42:55,670 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:42:57,643 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:42:57,689 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:42:59,690 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:42:59,719 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:01,737 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:01,771 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:03,784 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:03,813 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:04,898 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8962) : connect successfully!
2017-05-13 22:43:05,935 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:05,965 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:07,987 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:08,017 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:10,138 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:10,181 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:10,616 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:10,656 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:12,180 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:12,222 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:14,233 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:14,263 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:16,377 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:16,404 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:18,426 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-13 22:43:18,479 - Mainserverlog -log.py[line:26]-INFO -data insert ok!
2017-05-13 22:43:20,475 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.3', 54280) : lost connect
2017-05-13 22:56:16,394 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-13 22:56:38,271 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-13 22:56:54,913 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.1', 9393) : connect successfully!
2017-05-13 22:58:14,506 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.1', 9393) : lost connect
2017-05-13 23:03:06,973 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.1', 9470) : connect successfully!
2017-05-13 23:03:38,596 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '192.168.191.1', 9470) : lost connect
2017-05-14 22:45:22,419 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:45:35,820 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 7972) : connect successfully!
2017-05-14 22:46:52,642 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:46:55,891 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 7998) : connect successfully!
2017-05-14 22:46:57,868 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 7998) : lost connect
2017-05-14 22:47:20,710 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8006) : connect successfully!
2017-05-14 22:47:22,483 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8006) : lost connect
2017-05-14 22:48:06,375 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:48:07,904 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8047) : connect successfully!
2017-05-14 22:48:09,657 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-14 22:48:09,658 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'AttributeError'>: 'sql_operate' object has no attribute 'query'
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:92:action
]
2017-05-14 22:48:31,433 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-14 22:48:31,434 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'AttributeError'>: 'sql_operate' object has no attribute 'query'
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:92:action
]
2017-05-14 22:50:11,327 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:50:14,122 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8080) : connect successfully!
2017-05-14 22:50:16,547 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-14 22:50:16,548 - Mainserverlog -log.py[line:35]-ERROR -insert wrong!
2017-05-14 22:51:11,568 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:51:13,991 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8103) : connect successfully!
2017-05-14 22:51:15,432 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-14 22:51:15,433 - Mainserverlog -log.py[line:35]-ERROR -insert wrong!
2017-05-14 22:51:25,496 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-14 22:51:25,496 - Mainserverlog -log.py[line:35]-ERROR -insert wrong!
2017-05-14 22:53:50,357 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:53:52,872 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8145) : connect successfully!
2017-05-14 22:53:54,463 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-14 22:53:54,463 - Mainserverlog -log.py[line:26]-INFO -select  ok!
2017-05-14 22:54:10,616 - Mainserverlog -log.py[line:26]-INFO -callback is 1
2017-05-14 22:54:10,617 - Mainserverlog -log.py[line:35]-ERROR -query wrong!
2017-05-14 22:57:47,342 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:57:50,255 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8222) : connect successfully!
2017-05-14 22:57:51,970 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8222) : lost connect
2017-05-14 22:58:11,532 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:58:14,586 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8239) : connect successfully!
2017-05-14 22:58:17,589 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8239) : lost connect
2017-05-14 22:58:35,771 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:58:38,445 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8254) : connect successfully!
2017-05-14 22:58:40,155 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8254) : lost connect
2017-05-14 22:58:40,155 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'KeyError'>: <MProtocol #0 on 8889>
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:89:action
]
2017-05-14 22:59:03,331 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 22:59:06,331 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8270) : connect successfully!
2017-05-14 22:59:08,006 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'KeyError'>: <MProtocol #0 on 8889>
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:89:action
]
2017-05-14 23:10:13,383 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:10:17,917 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8448) : connect successfully!
2017-05-14 23:10:20,768 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8448) : lost connect
2017-05-14 23:10:20,768 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'KeyError'>: <MProtocol #0 on 8889>
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:89:action
]
2017-05-14 23:10:49,706 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:10:50,598 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8464) : connect successfully!
2017-05-14 23:10:53,612 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'KeyError'>: <MProtocol #0 on 8889>
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:89:action
]
2017-05-14 23:11:01,899 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'KeyError'>: <MProtocol #0 on 8889>
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:89:action
]
2017-05-14 23:11:32,081 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:11:34,436 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8490) : connect successfully!
2017-05-14 23:11:34,925 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8490) : lost connect
2017-05-14 23:11:37,123 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8495) : connect successfully!
2017-05-14 23:11:39,642 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'KeyError'>: <MProtocol #1 on 8889>
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:89:action
]
2017-05-14 23:12:49,899 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:12:52,632 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8526) : connect successfully!
2017-05-14 23:12:56,092 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'KeyError'>: <MProtocol #0 on 8889>
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:89:action
]
2017-05-14 23:13:48,585 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8526) : lost connect
2017-05-14 23:14:27,332 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:14:31,537 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8559) : connect successfully!
2017-05-14 23:14:35,388 - Mainserverlog -log.py[line:35]-ERROR -[Failure instance: Traceback: <class 'KeyError'>: <MProtocol #0 on 8889>
F:\python35\lib\threading.py:914:_bootstrap_inner
F:\python35\lib\threading.py:862:run
F:\python35\lib\site-packages\twisted\_threads\_threadworker.py:46:work
F:\python35\lib\site-packages\twisted\_threads\_team.py:190:doWork
--- <exception caught here> ---
F:\python35\lib\site-packages\twisted\python\threadpool.py:250:inContext
F:\python35\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
F:\python35\lib\site-packages\twisted\python\context.py:122:callWithContext
F:\python35\lib\site-packages\twisted\python\context.py:85:callWithContext
F:\pycharm\pycharmWorkplace\PyServer\pyServer\src\datahandle.py:89:action
]
2017-05-14 23:14:59,649 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:15:01,540 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8576) : connect successfully!
2017-05-14 23:15:03,791 - Mainserverlog -log.py[line:26]-INFO -select  ok!
2017-05-14 23:22:28,679 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:22:31,400 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 8992) : connect successfully!
2017-05-14 23:22:33,210 - Mainserverlog -log.py[line:26]-INFO -select  ok!
2017-05-14 23:27:26,018 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:27:29,293 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9177) : connect successfully!
2017-05-14 23:27:32,475 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9177) : lost connect
2017-05-14 23:28:09,250 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:28:11,327 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9214) : connect successfully!
2017-05-14 23:28:12,993 - Mainserverlog -log.py[line:26]-INFO -select  ok!
2017-05-14 23:28:46,164 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:28:49,179 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9235) : connect successfully!
2017-05-14 23:28:51,540 - Mainserverlog -log.py[line:26]-INFO -select  ok!
2017-05-14 23:31:51,475 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9235) : lost connect
2017-05-14 23:31:53,084 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9316) : connect successfully!
2017-05-14 23:32:21,301 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9316) : lost connect
2017-05-14 23:32:25,173 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9337) : connect successfully!
2017-05-14 23:34:19,639 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9337) : lost connect
2017-05-14 23:36:47,779 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:36:54,423 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9411) : connect successfully!
2017-05-14 23:37:00,826 - Mainserverlog -log.py[line:26]-INFO -select  ok!
2017-05-14 23:37:10,087 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9421) : connect successfully!
2017-05-14 23:37:15,097 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9421) : lost connect
2017-05-14 23:45:33,303 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:45:40,055 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 9877) : connect successfully!
2017-05-14 23:47:42,064 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:47:43,448 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 10101) : connect successfully!
2017-05-14 23:48:01,017 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 10109) : connect successfully!
2017-05-14 23:48:02,762 - Mainserverlog -log.py[line:26]-INFO -select  ok!
2017-05-14 23:48:09,006 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 10101) : lost connect
2017-05-14 23:48:30,908 - Mainserverlog -log.py[line:26]-INFO -reactor start...ok!
2017-05-14 23:48:34,790 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 10132) : connect successfully!
2017-05-14 23:48:37,139 - Mainserverlog -log.py[line:26]-INFO -select  ok!
2017-05-14 23:48:45,630 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 10137) : connect successfully!
2017-05-14 23:49:00,096 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 10142) : connect successfully!
2017-05-14 23:49:02,464 - Mainserverlog -log.py[line:26]-INFO -select  ok!
2017-05-14 23:49:10,515 - Mainserverlog -log.py[line:26]-INFO -ip:IPv4Address(TCP, '127.0.0.1', 10151) : connect successfully!
